sudo: required
services:
  - docker

before_install:
  - docker build -t cloudrck/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cloudrck/react-test npm test

after_sucess:
  - docker build -t cloudrck/multi-client ./client
  - docker build -t cloudrck/multi-nginx ./nginx
  - docker build -t cloudrck/multi-server ./server
  - docker build -t cloudrck/multi-worker ./worker
  # Login to Docker Hub CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Push images to Docker Hub
  - docker push cloudrck/multi-client
  - docker push cloudrck/multi-nginx
  - docker push cloudrck/multi-server
  - docker push cloudrck/multi-worker
